/*
Deployment script for MddpMrDemo

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "MddpMrDemo"
:setvar DefaultFilePrefix "MddpMrDemo"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key 727ba0d4-d954-4a9b-9b26-6c7979b16405 is skipped, element [dbo].[FK_Resource_ToTable] (SqlForeignKeyConstraint) will not be renamed to [FK_Resource_ResourceType]';


GO
PRINT N'Creating Table [dbo].[DbVersion]...';


GO
CREATE TABLE [dbo].[DbVersion] (
    [Number]    NVARCHAR (50)  NOT NULL,
    [CreatedOn] DATETIME2 (7)  NOT NULL,
    [CreatedBy] NVARCHAR (255) NOT NULL,
    CONSTRAINT [PK_DbVersionId] PRIMARY KEY CLUSTERED ([Number] ASC)
);


GO
PRINT N'Creating Table [dbo].[HierarchyTree]...';


GO
CREATE TABLE [dbo].[HierarchyTree] (
    [Id]                INT NOT NULL,
    [ResourceId]        INT NOT NULL,
    [ResourceParentId]  INT NULL,
    [ResourceManagerId] INT NULL,
    CONSTRAINT [PK_HierarchyTreeId] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Resource]...';


GO
CREATE TABLE [dbo].[Resource] (
    [Id]             INT            NOT NULL,
    [Name]           NVARCHAR (100) NOT NULL,
    [ResourceTypeId] SMALLINT       NOT NULL,
    CONSTRAINT [PK_ResourceId] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[ResourceType]...';


GO
CREATE TABLE [dbo].[ResourceType] (
    [Id]   SMALLINT      NOT NULL,
    [Name] NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Foreign Key [dbo].[FK_HierarchyTreeResourceId_ResourceId]...';


GO
ALTER TABLE [dbo].[HierarchyTree] WITH NOCHECK
    ADD CONSTRAINT [FK_HierarchyTreeResourceId_ResourceId] FOREIGN KEY ([ResourceId]) REFERENCES [dbo].[Resource] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_HierarchyTreeResourceParentId_ResourceId]...';


GO
ALTER TABLE [dbo].[HierarchyTree] WITH NOCHECK
    ADD CONSTRAINT [FK_HierarchyTreeResourceParentId_ResourceId] FOREIGN KEY ([ResourceParentId]) REFERENCES [dbo].[Resource] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_HierarchyTreeResourceManagerId_ResourceId]...';


GO
ALTER TABLE [dbo].[HierarchyTree] WITH NOCHECK
    ADD CONSTRAINT [FK_HierarchyTreeResourceManagerId_ResourceId] FOREIGN KEY ([ResourceManagerId]) REFERENCES [dbo].[Resource] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ResourceTypeId_ResourceTypeId]...';


GO
ALTER TABLE [dbo].[Resource] WITH NOCHECK
    ADD CONSTRAINT [FK_ResourceTypeId_ResourceTypeId] FOREIGN KEY ([ResourceTypeId]) REFERENCES [dbo].[ResourceType] ([Id]);


GO
PRINT N'Creating Trigger [dbo].[TR_DbVersion_InsteadOfInsert]...';


GO

CREATE TRIGGER [dbo].[TR_DbVersion_InsteadOfInsert] ON [dbo].[DbVersion]
INSTEAD OF INSERT AS
BEGIN
	INSERT INTO [dbo].[DbVersion] ([Number], [CreatedOn], [CreatedBy])
	SELECT i.Number, GETDATE(), SUSER_NAME()
	FROM INSERTED i
END;
GO
-- Refactoring step to update target server with deployed transaction logs

IF OBJECT_ID(N'dbo.__RefactorLog') IS NULL
BEGIN
    CREATE TABLE [dbo].[__RefactorLog] (OperationKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY)
    EXEC sp_addextendedproperty N'microsoft_database_tools_support', N'refactoring log', N'schema', N'dbo', N'table', N'__RefactorLog'
END
GO
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '727ba0d4-d954-4a9b-9b26-6c7979b16405')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('727ba0d4-d954-4a9b-9b26-6c7979b16405')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[HierarchyTree] WITH CHECK CHECK CONSTRAINT [FK_HierarchyTreeResourceId_ResourceId];

ALTER TABLE [dbo].[HierarchyTree] WITH CHECK CHECK CONSTRAINT [FK_HierarchyTreeResourceParentId_ResourceId];

ALTER TABLE [dbo].[HierarchyTree] WITH CHECK CHECK CONSTRAINT [FK_HierarchyTreeResourceManagerId_ResourceId];

ALTER TABLE [dbo].[Resource] WITH CHECK CHECK CONSTRAINT [FK_ResourceTypeId_ResourceTypeId];


GO
PRINT N'Update complete.';


GO
